name: ci

on:
  push:

env:
  REGISTRY: acc-test-cr-cn-guangzhou.cr.volces.com 
  IMAGE_NAME: ${{ github.repository }} 

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: acc-test-cr-cn-guangzhou.cr.volces.com
          username: liyiting@55177030
          password: 1qaz!QAZ
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/acc-test-namespace/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=
            type=semver,pattern={{version}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}